package com.dungeoncraft.mixin.client;

import com.dungeoncraft.DungeonCraft;
import com.dungeoncraft.block.StonekeepChestFacing;
import com.dungeoncraft.block.StonekeepLowDungeonChestBlock;
import com.dungeoncraft.block.StonekeepLowDungeonChestPartBlock;
import net.minecraft.client.Minecraft;
import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.client.multiplayer.MultiPlayerGameMode;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.world.level.block.state.BlockState;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.ModifyVariable;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

/**
 * Makes every occupied cell of the Stonekeep chest behave like one chest while
 * it is mined and destroyed.
 *
 * Mining a helper cell is redirected to the master so the block-entity
 * renderer receives normal destruction progress.
 *
 * Cardinal chests add the normal helper-cell destruction effect here.
 * Diagonal final particles are handled separately by the ClientLevel mixin.
 */
@Mixin(MultiPlayerGameMode.class)
public abstract class StonekeepChestBreakRedirectMixin {

    /**
     * Adds the normal helper-cell destruction effect for cardinal chests.
     *
     * Diagonal chests return here because their complete controlled particle
     * effect is generated by StonekeepChestDiagonalDestroyParticleMixin.
     */
    @Inject(
            method = "destroyBlock(Lnet/minecraft/core/BlockPos;)Z",
            at = @At("HEAD")
    )
    private void dungeoncraft$addStonekeepCardinalHelperDestroyEffect(
            BlockPos clickedPos,
            CallbackInfoReturnable<Boolean> callbackInfo
    ) {
        ClientLevel level = Minecraft.getInstance().level;
        if (level == null) {
            return;
        }

        BlockPos masterPos = dungeoncraft$findStonekeepMaster(level, clickedPos);
        if (masterPos == null) {
            return;
        }

        BlockState masterState = level.getBlockState(masterPos);
        StonekeepChestFacing facing =
                masterState.getValue(StonekeepLowDungeonChestBlock.FACING);

        if (facing.isDiagonal()) {
            return;
        }

        for (Direction helperDirection : facing.helperDirections()) {
            BlockPos helperPos = masterPos.relative(helperDirection);
            BlockState helperState = level.getBlockState(helperPos);

            if (helperState.is(DungeonCraft.STONEKEEP_LOW_DUNGEON_CHEST_PART)
                    && StonekeepLowDungeonChestPartBlock
                    .getMasterPos(helperPos, helperState)
                    .equals(masterPos)) {
                level.addDestroyBlockEffect(helperPos, helperState);
            }
        }
    }

    /**
     * Redirects helper-cell mining to the master before vanilla calculates
     * progress, sound, prediction, and final destruction.
     */
    @ModifyVariable(
            method = {
                    "destroyBlock(Lnet/minecraft/core/BlockPos;)Z",
                    "startDestroyBlock(Lnet/minecraft/core/BlockPos;Lnet/minecraft/core/Direction;)Z",
                    "continueDestroyBlock(Lnet/minecraft/core/BlockPos;Lnet/minecraft/core/Direction;)Z"
            },
            at = @At("HEAD"),
            argsOnly = true,
            ordinal = 0
    )
    private BlockPos dungeoncraft$redirectStonekeepPartBreakToMaster(
            BlockPos clickedPos
    ) {
        ClientLevel level = Minecraft.getInstance().level;
        if (level == null) {
            return clickedPos;
        }

        BlockPos masterPos = dungeoncraft$findStonekeepMaster(level, clickedPos);
        return masterPos != null ? masterPos : clickedPos;
    }

    /** Returns the chest master for either a master or helper target. */
    private static BlockPos dungeoncraft$findStonekeepMaster(
            ClientLevel level,
            BlockPos clickedPos
    ) {
        BlockState clickedState = level.getBlockState(clickedPos);

        if (clickedState.is(DungeonCraft.STONEKEEP_LOW_DUNGEON_CHEST)) {
            return clickedPos;
        }

        if (!clickedState.is(DungeonCraft.STONEKEEP_LOW_DUNGEON_CHEST_PART)) {
            return null;
        }

        BlockPos masterPos =
                StonekeepLowDungeonChestPartBlock.getMasterPos(
                        clickedPos,
                        clickedState
                );

        return level.getBlockState(masterPos)
                .is(DungeonCraft.STONEKEEP_LOW_DUNGEON_CHEST)
                ? masterPos
                : null;
    }
}
